name: CMake Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up CMake
      uses: lukka/run-cmake@v10.7
      with:
        cmakeListsTxtPath: ./CMakeLists.txt
        buildPresetCmdString: [`--build`]

    - name: Build
      run: |
        cmake --build .
