name: CMake Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: lukka/get-cmake@latest
    - name: Set up CMake
      uses: lukka/run-cmake@latest
      with:
        cmakeListsOrSettingsJson: .

    - name: Build
      run: |
        cmake --build _builds
